api/urls.py
from django.urls import path
from api.views.user import UserLoginRegisterView, logout_view, UserUpdateInfoView, UserUpdatePasswordView, \
    UserLoginRenderView, UserRegisterRenderView
from api.views.cart import CartRenderView, CartDeleteAllView, CartQuantityDelView, CartQuantityAddView
from api.views.cartitem import CartItemCreateView, CartItemDeleteView
from api.views.product import ProductListView, ProductDetailView, ProductListByCategoryView, ProductForOrdersListView, \
    ProductForCatalogListView, SearchProductListView
from api.views.order import OrderRenderCreateView, OrderListView, ReceptRenderView, ReceptRender1View, \
    OrderItemDeleteView, UserSettingsRenderView

urlpatterns = [
    # render
    path("", ProductListView.as_view(), name="index"),
    path("cart/", CartRenderView.as_view(), name="cart"),
    path("order/", OrderRenderCreateView.as_view(), name="order"),
    path('user/login/', UserLoginRenderView.as_view(), name='login'),
    path('user/register/', UserRegisterRenderView.as_view(), name='register'),
    path('user/recept/', ReceptRenderView.as_view(), name='recept'),
    path('user/recept1/', ReceptRender1View.as_view(), name='recept1'),
    path('user/settings/', UserSettingsRenderView.as_view(), name='settings'),

    # product
    path("catalog/", ProductForCatalogListView.as_view(), name="catalog"),
    path("product/<int:id>/", ProductDetailView.as_view(), name="detail"),
    path("categories/<int:id>/product/", ProductListByCategoryView.as_view(), name="categories"),

    path("search/", SearchProductListView.as_view(), name="search"),

    # cart
    path("cart/delete_all/", CartDeleteAllView.as_view(), name="clear_cart"),

    path("cart/<int:id>/quantity_add/", CartQuantityAddView.as_view(), name="item_quantity_add"),
    path("cart/<int:id>/quantity_del/", CartQuantityDelView.as_view(), name="item_quantity_del"),

    # cart items
    path("cart/product/<int:id>/create/", CartItemCreateView.as_view(), name="add_to_cart"),
    path("cart/product/<int:id>/delete/", CartItemDeleteView.as_view(), name="delete_from_cart"),

    # order
    path("order/product/<int:id>/delete/", OrderItemDeleteView.as_view(), name="delete_from_order"),

    # user
    path('user/', UserLoginRegisterView.as_view(), name='user'),
    path('user/logout/', logout_view, name='logout'),
    path('user/orders/', OrderListView.as_view(), name='user_orders'),
    path('user/products/', ProductForOrdersListView.as_view(), name='user_products'),
    path('user/change_info/', UserUpdateInfoView.as_view(), name='user_info'),
    path('user/change_pass/', UserUpdatePasswordView.as_view(), name='user_pass'),
]

models_app/models/product/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    image = models.ImageField(upload_to='img/category/', verbose_name='Изображение')
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name='categories',
                                 verbose_name='Категория')
    price = models.IntegerField(default=0, verbose_name='Цена')
    country = models.CharField(max_length=255, verbose_name='Страна производителя')

    RECEPT = 'Recept'
    NOT_RECEPT = 'not recept'

    VACATION_CHOICES = (
        (RECEPT, 'С рецептом'),
        (NOT_RECEPT, 'Без рецепта'),
    )
    vacation = models.CharField(max_length=20, choices=VACATION_CHOICES, verbose_name='Отпуск', default=NOT_RECEPT)
    expiration_date = models.CharField(max_length=50, verbose_name='Срок годности')
    description = models.TextField(verbose_name='Описание')
    quantity = models.IntegerField(default=1, verbose_name='Количесвто')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'products'
        app_label = "models_app"
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

api/views/cart.py
from django.db.models import Sum
from django.shortcuts import render
from django.views import View

from models_app.models import Cart, CartItem


class CartRenderView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            cart = Cart.objects.get(user=request.user)
            cart_items = CartItem.objects.filter(cart=cart)
            total_sum = 0
            for item in cart_items:
                total_sum += item.product.price * item.quantity
            return render(request, "basket.html", context={
                "cart_items": cart_items,
                "summ": total_sum,
            })
        else:
            return render(request, "basket.html")


class CartDeleteAllView(View):

    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=cart)
        for item in cart_items:
            item.delete()
        return render(request, "basket.html")


class CartQuantityAddView(View):
    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.get(cart=cart, product_id=kwargs["id"])
        cart_items.quantity += 1
        cart_items.save()
        cart_items = CartItem.objects.filter(cart=cart)
        total_sum = 0
        for item in cart_items:
            total_sum+=item.product.price*item.quantity

        return render(request, "basket.html", context={
            "cart_items":cart_items,
            "summ": total_sum,
        })


class CartQuantityDelView(View):
    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.get(cart=cart, product_id=kwargs["id"])
        if not cart_items.quantity - 1 == 0:
            cart_items.quantity -= 1
            cart_items.save()
        cart_items = CartItem.objects.filter(cart=cart)
        total_sum = 0
        for item in cart_items:
            total_sum += item.product.price * item.quantity
        return render(request, "basket.html", context={
            "cart_items": cart_items,
            "summ": total_sum,
        })

api/views/cartitem.py
from django.db.models import Sum
from django.shortcuts import redirect, render
from django.views import View
from models_app.models import Cart, Product
from models_app.models import CartItem


class CartItemCreateView(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(id=kwargs["id"])
        cartitem = CartItem.objects.filter(product=product, cart=Cart.objects.get(user=request.user))
        if not cartitem.exists():
            if product.quantity > 0:
                CartItem.objects.create(
                    product=Product.objects.get(id=kwargs["id"]),
                    cart=Cart.objects.get(user=request.user),
                    quantity=request.GET.get("quantity", 1)
                )
        return render(request, "card.html", context={
            "product": Product.objects.get(id=kwargs["id"]),
            "added": True if CartItem.objects.filter(product_id=kwargs["id"],
                                                     cart=Cart.objects.get(user=request.user)
                                                     ).exists() else "",
        })


class CartItemDeleteView(View):

    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_item = CartItem.objects.get(product_id=kwargs["id"], cart=cart)
        cart_item.delete()
        cart_items = CartItem.objects.filter(cart=cart)
        total_sum = 0
        for item in cart_items:
            total_sum += item.product.price * item.quantity
        return render(request, "basket.html", context={
            "cart_items": cart_items,
            "summ": total_sum,
        })

api/views/category.py
import sys

from django.shortcuts import render
from django.views import View
from models_app.models import Product
from models_app.models import Category


class CategoryProductListView(View):

    def get(self, request, *args, **kwargs):
        vacation = request.GET.get("vacation")
        price_start = request.GET.get("price", 0)
        price_end = request.GET.get("price", sys.maxsize)
        if vacation or price_start or price_end:
            products = Product.objects.filter(
                price__gte=price_start,
                price__lte=price_end,
                vacation=vacation,
                category_id=kwargs["id"]
            ).order_by(request.GET.get("order", "id"))
        else:
            products = Product.objects.filter(
                category_id=kwargs["id"]
            )
        return render(request, "", context={
            "products": products,
            "categories": Category.objects.all()
        })

api/views/order.py
from django.shortcuts import render
from django.views import View

from models_app.models import Cart, CartItem, Order, CartItemOrder
import random


class OrderRenderCreateView(View):

    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=cart)
        return render(request, "login.html", context={
            "cart_items": cart_items,
        })

    def post(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=cart)
        number = ''  # предварительно создаем переменную psw
        for x in range(12):
            number = number + random.choice(list('123456789qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM'))
        total_sum = 0
        for item in cart_items:
            total_sum += item.product.price * item.quantity
        order = Order.objects.create(user=request.user, number=number, adress=request.POST['adress'],
                                     total_price=total_sum)
        for item in cart_items:
            CartItemOrder.objects.create(order=order, product=item.product, quantity=item.quantity)
            item.delete()
        return render(request, "basket.html", context={
            "cart_items": cart_items,
        })


class OrderListView(View):

    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(user=request.user)
        result = []
        for order in orders:
            result += [[order, CartItemOrder.objects.filter(order=order)]]
        return render(request, "user/index.html", context={
            "result": result,
        })


class OrderItemDeleteView(View):

    def get(self, request, *args, **kwargs):
        cart = Cart.objects.get(user=request.user)
        cart_item = CartItem.objects.get(product_id=kwargs["id"], cart=cart)
        cart_item.delete()
        cart_items = CartItem.objects.filter(cart=cart)
        return render(request, "login.html", context={
            "cart_items": cart_items,
        })


class ReceptRenderView(View):

    def get(self, request, *args, **kwargs):
        return render(request, "user/recept.html")


class ReceptRender1View(View):

    def get(self, request, *args, **kwargs):
        return render(request, "user/recept2.html")


class UserSettingsRenderView(View):

    def get(self, request, *args, **kwargs):
        return render(request, "user/settings.html")

api/views/product.py
import sys

from django.db.models import Value
from django.shortcuts import render
from django.views import View
from models_app.models import Product, Order, CartItemOrder, Cart
from models_app.models import Category, CartItem


class ProductListView(View):

    def get(self, request, *args, **kwargs):
        products = Product.objects.all().annotate(added=Value(False))
        for product in products:
            product.added = True if CartItem.objects.filter(product_id=product.id) else ""
        if len(products) > 5:
            products = products[:5]
        return render(request, "index.html", context={
            "popular_products": products,
            "categories": Category.objects.all()
        })


class ProductForCatalogListView(View):

    def get(self, request, *args, **kwargs):
        products = Product.objects.all().annotate(added=Value(False))
        for product in products:
            product.added = True if CartItem.objects.filter(product_id=product.id) else ""
        return render(request, "katalaog.html", context={
            "products": products,
            "categories": Category.objects.all()
        })


class ProductForOrdersListView(View):

    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(user=request.user)
        product_list = []
        for order in orders:
            items = CartItemOrder.objects.filter(order=order)
            for item in items:
                product_list.append(item.product)
        return render(request, "user/products.html", context={
            "products": set(product_list)
        })


class ProductDetailView(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(id=kwargs["id"])
        added = ""
        if request.user.is_authenticated:
            added = True if CartItem.objects.filter(product_id=product.id,
                                                    cart=Cart.objects.get(user=request.user)) else ""
        return render(request, "card.html", context={
            "product": product,
            "categories": Category.objects.all(),
            "added": added,
        })


class ProductListByCategoryView(View):

    def get(self, request, *args, **kwargs):
        vacation_1 = request.GET.get("vacation_1")
        vacation_2 = request.GET.get("vacation_2")
        price_start = request.GET.get("price_start") or 0
        price_end = request.GET.get("price_end") or sys.maxsize
        if price_start or price_end:
            products = Product.objects.filter(
                price__gte=price_start,
                price__lte=price_end,
            ).annotate(added=Value(False)).order_by(request.GET.get("radio", "id"))
        else:
            products = Product.objects.all().annotate(added=Value(False)).order_by(request.GET.get("radio", "id"))
        if vacation_1:
            products = products.filter(
                vacation=Product.NOT_RECEPT
            )
        if vacation_2:
            products = products.filter(
                vacation=Product.RECEPT
            )
        context = {}
        if kwargs.get("id") != 0:
            products = products.filter(
                category_id=kwargs["id"]
            )
            context["active_category"] = kwargs.get("id")
        for product in products:
            product.added = True if CartItem.objects.filter(product_id=product.id) else ""
        return render(request, "katalaog.html", context={
                                                            "products": products,
                                                            "categories": Category.objects.all()
                                                        } | context)


class SearchProductListView(View):

    def get(self, request, *args, **kwargs):
        products = Product.objects.filter(title__icontains=request.GET.dict().get("lname", ""))
        return render(request, "katalaog.html", context={
            "categories": Category.objects.all(),
            "products": products
        })

api/templates/basket.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Корзина</title>
    <link rel="stylesheet" href="{% static 'css/backet-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/backet-inner-style.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
            rel="stylesheet"/>
</head>
<body>
<div class="city-head">
    <h2 class="city-text">
        Ваш город: <a class="city-href" href="">Москва</a>
    </h2>
    <h2 class="city-text2">Помощь покупателям</h2>
</div>
<div class="nav-bar">
    <a href="{% url 'index' %}"
    ><img class="nav-bar-logo" src="{% static 'img/Logotype.png' %}" alt=""
    /></a>
    <div class="nav-search-div">
        <form action="{% url 'search' %}">
            <button type="submit" class="search-form-nav-btn">
                <img src="{% static 'img/Round.png'%}" alt=""/>
            </button>
            <input type="search" id="lname" name="lname" placeholder="Поиск"/>
        </form>
    </div>
    <div class="icon-cards">
         {% if request.user.is_authenticated %}
        <div class="icon">
          <img class="stat-icon" src="{% static 'img/off.png'%}" alt="" />
          <a class="icon-cards-text" href="{%url 'user_orders'%}">{{user}}</a>
        </div>
        {% else %}
        <div class="icon">
          <img class="stat-icon" src="{% static 'img/off.png'%}" alt="" />
          <a class="icon-cards-text" href="{%url 'login'%}">Войти</a>
        </div>
        {% endif %}

        <div class="icon">
          <img src="{% static 'img/like.png'%}" alt="" />
          {% if request.user.is_authenticated %}
          <a class="icon-cards-text" href="{%url 'user_orders'%}">Заказы</a>
          {% else %}
          <a class="icon-cards-text">Заказы</a>
          {% endif %}
        </div>
        <div class="icon">
          <img class="basket-icon" src="{% static 'img/backet.png'%}" alt="" />
          <a class="icon-cards-text" href="{% url 'cart' %}">Корзина</a>
        </div>
      </div>
    </div>
</div>

<div class="href">
    <a href="{% url 'index' %}">Главная ></a>
    <a href="{%url 'cart'%}">Корзина</a>
</div>

{% if request.user.is_authenticated %}

{% if summ %}
<div class="basket-all">
    <div class="title-and-filters">
        <h1>Корзина</h1>
        <button class="clear-btn"><a href="{% url 'clear_cart' %}">Очистить корзину</a></button>
    </div>

    <div class="box">
        <div class="card-basket-all">
            {% for item in cart_items %}
            <div class="card">
                <img class="img-medicament" src="{{ item.product.image.url }}" alt=""/>
                <div class="title-card">
                    <h2>{{ item.product.title }}</h2>
                </div>
                <div class="counter">
                    <a href="{% url 'item_quantity_del' item.product.id %}">
                        <button class="decrease" type="button">-</button>
                    </a>

                    <a href="{% url 'item_quantity_add' item.product.id %}">
                        <button class="increase" type="button">+</button>
                    </a>
                    <input
                            class="counter-quantity"
                            id="quantityid"
                            type="text"
                            name="field"
                            value="{{ item.quantity }}"/>
                </div>
                <h4 class="price-card">{{ item.product.price }} ₽</h4>
                <a href="{% url 'delete_from_cart' item.product.id %}">
                    <button class="vector-btn">x</button>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="itog-card">
            <h1 class="summa">Итого: {{ summ }} ₽</h1>
            <button class="btn-in-basket">
                <a href="{% url 'order'%}">Перейти к оформлению</a>
            </button>
        </div>
    </div>

    {% else %}
        <div class="cart-is-empty">
            <h1>Ваша корзина пуста</h1>
            <img src="{% static 'img/shop-cart.png' %}" alt=""/>
            <p>Для выбора товара пепрейдите в каталог или воспользуйтесь поиском</p>
        </div>
    {% endif %}

</div>
{% else %}
<div class="block-login">
    <h4>Авторизируйтесь что бы смотреть</h4>
</div>
{% endif %}



<footer>
    <div class="footer-content">
        <div class="about-we">
            <h1>О нас</h1>
            <ul>
                <li><a href="#">О сервисе </a></li>
                <li><a href="#">Реквизиты</a></li>
                <li><a href="#">Контакты</a></li>
                <li><a href="#">Обратная связь</a></li>
            </ul>
        </div>
        <div class="user">
            <h1>Пользователям</h1>
            <ul>
                <li><a href="#">Как сделать заказ</a></li>
                <li><a href="#">Доставка и оплата</a></li>
                <li><a href="#">Условия возврата</a></li>
                <li><a href="#">Вопросы и ответы</a></li>
                <li><a href="#">Безопасность платежей</a></li>
            </ul>
        </div>
        <div class="partner">
            <h1>Партнерам</h1>
            <ul>
                <li><a href="#">Подключение вашей аптеки</a></li>
                <li><a href="#">Производителям, брендам</a></li>
            </ul>
        </div>
    </div>
    <div class="line"></div>
    <h4 class="finish-text">
        © 2023 По Рецепту <br/>
        Все права защищены
    </h4>
</footer>
<script src="script.js"></script>
</body>
</html>

api/templates/card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>О товаре</title>
    <link rel="stylesheet" href="{% static 'css/style-card.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
</head>
<body>
    <div class="city-head">
        <h2 class="city-text">Ваш город: <a class="city-href" href="">Москва</a></h2>
        <h2 class="city-text2">Помощь покупателям</h2>
    </div>
    <div class="nav-bar">
        <a href="{% url 'index' %}"><img class="nav-bar-logo" src="{% static 'img/Logotype.png'%}" alt=""></a>
<!-- Модальный -->
            <div class="nav-search-div">
                <form action="{% url 'search' %}">
            <button type="submit" class="search-form-nav-btn">
              <img src="{% static 'img/Round.png'%}" alt=""/>
            </button>
            <input type="search" id="lname" name="lname" placeholder="Поиск" />
        </form>
            </div>
            <div class="icon-cards">
         {% if request.user.is_authenticated %}
        <div class="icon">
          <img class="stat-icon" src="{% static 'img/off.png'%}" alt="" />
          <a class="icon-cards-text" href="{%url 'user_orders'%}">{{user}}</a>
        </div>
        {% else %}
        <div class="icon">
          <img class="stat-icon" src="{% static 'img/off.png'%}" alt="" />
          <a class="icon-cards-text" href="{%url 'login'%}">Войти</a>
        </div>
        {% endif %}

        <div class="icon">
          <img src="{% static 'img/like.png'%}" alt="" />
          {% if request.user.is_authenticated %}
          <a class="icon-cards-text" href="{%url 'user_orders'%}">Заказы</a>
          {% else %}
          <a class="icon-cards-text">Заказы</a>
          {% endif %}
        </div>
        <div class="icon">
          <img class="basket-icon" src="{% static 'img/backet.png'%}" alt="" />
          <a class="icon-cards-text" href="{% url 'cart' %}">Корзина</a>
        </div>
      </div>
    </div>
    </div>

    <div class="content-box">
        <div class="card-tablet">
            <img class="main-img" src="{{ product.image.url }}">
        </div>
        <div class="text-content-box">
            <h1>{{ product.title }}</h1>
           <div class="text-content-all">
            <div class="givli1">
                <ul>
                    <li>Категория:</li>
                    <li>Страна происхождения:</li>
                    <li>Порядок отпуска:</li>
                    <li>Срок годности:</li>
                </ul>
            </div>
            <div class="givli2">
                <ul>
                   <li>{{ product.category.title }}</li>
                   <li>{{ product.country }}</li>
                   <li>{{ product.get_vacation_display }}</li>
                   <li>{{ product.expiration_date }}</li>
                </ul>
            </div>
            <div class="hug-card">
                <h3>Цена от {{ product.price }} р.</h3>
                {% if product.quantity %}
                    <p>В наличии </p>
                {% if user.is_authenticated %}
                  {% if added %}
                    <button class="btn-in-basket">Уже в коризине</button>
                  {% else %}
                  <button class="btn-in-basket"><a href="{% url 'add_to_cart' product.id %}">В корзину</a></button>
                  {% endif %}
                {% else %}
                      <button disabled class="btn-in-basket"><a>В корзину</a></button>
                {%endif%}
                {% else %}
                        <p>Нет в наличии </p>
                {% endif %}

            </div>
           </div>
        </div>
    </div>
    <div class="text-overview">
        <div class="overview-nav">
        <ul>
            <li><a href="">Описание</a></li>
        </ul>
        </div>
        <div class="overview">
            <p class="tone">
                {{ product.description }}
            </p>

        </div>
    </div>

    <footer>
        <div class="footer-content">
            <div class="about-we">
                <h1>О нас</h1>
                <ul>
                <li><a href="#">О сервисе </a></li>
                <li><a href="#">Реквизиты</a></li>
                <li><a href="#">Контакты</a></li>
                <li><a href="#">Обратная связь</a></li>
            </ul>
            </div>
            <div class="user">
                <h1>Пользователям</h1>
                <ul>
                    <li><a href="#">Как сделать заказ</a></li>
                    <li><a href="#">Доставка и оплата</a></li>
                    <li><a href="#">Условия возврата</a></li>
                    <li><a href="#">Вопросы и ответы</a></li>
                    <li><a href="#">Безопасность платежей</a></li>
                </ul>
            </div>
            <div class="partner">
                <h1>Партнерам</h1>
                <ul>
                    <li><a href="#">Подключение вашей аптеки</a></li>
                    <li><a href="#">Производителям, брендам</a></li>
                </ul>
            </div>
        </div>
        <div class="line"></div>
        <h4 class="finish-text">© 2023 По Рецепту <br> Все права защищены</h4>
    </footer>
    <script src="script.js">

    </script>
</body>
</html>

api/templates/registr.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Регистрация</title>
    <link rel="stylesheet" href="{% static 'css/registr-style.css'%}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet" />
  </head>
  <body>
    <div class="city-head">
      <h2 class="city-text">
        Ваш город: <a class="city-href" href="">Москва</a>
      </h2>
      <h2 class="city-text2">Помощь покупателям</h2>
    </div>
    <div class="nav-bar">
      <!-- навигация -->
      <a href="index.html"
        ><img class="nav-bar-logo" src="img/Logotype.png" alt=""
      /></a>

      <!-- Модальный -->

      <!-- строка поиска -->
      <div class="icon-cards">
        <div class="icon">
            <img class="stat-icon" src="{% static 'img/off.png'%}" alt=""/>
            <a class="icon-cards-text" href="{%url 'login'%}">Войти</a>
        </div>
        <div class="icon">
            <img src="{% static 'img/like.png'%}" alt=""/>
            <a class="icon-cards-text" href="login.html">Заказы</a>
        </div>
        <div class="icon">
            <img class="basket-icon" src="{% static 'img/backet.png'%}" alt=""/>
            <a class="icon-cards-text" href="basket.html">Корзина</a>
        </div>
    </div>
    </div>
    <!-- навигация по лекарствам -->

    <form action="{% url 'user' %}" method="post">
      {% csrf_token %}
      <div class="container">
        <h1>Регистрация</h1>
        <hr />
        <label for="email"><b>Введите email</b></label>
        <input type="text" placeholder="Enter Email" name="email" required />
        <label for="email"><b>Введите Логин</b></label>
        <input type="text" placeholder="Enter Login" name="username" required />
        <label for="psw"><b>Пароль</b></label>
        <input
          type="password"
          placeholder="Enter Password"
          name="password"
          required />

        <label for="psw-repeat"><b>Повторите пароль</b></label>
        <input
          type="password"
          placeholder="Repeat Password"
          name="psw-repeat"
          required />
        {% if error %}
        <p style="color: red">{{error}}</p>
        {%endif%}
        <hr />
        <button type="submit" class="registerbtn">
          <h3>Зарегистрироваться</h3>
        </button>
      </div>

      <div class="container signin">
        <p class="signin">
          Если у вас есть аккаут,<a href="{% url 'login'%}">Войдите</a>.
        </p>
      </div>
    </form>
    <script src="script.js"></script>
  </body>
</html>